config/routes.rb
Myspitch::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :employers

  devise_for :users

  resources :jobs do
    resources :entries
  end

  resources :candidates

  resources :candidate_feedbacks

  match "/j/:entry_hash" => "entries#apply", :as => :job_apply_direct
  match "/record/:entry_hash" => "entries#record", :as => :job_apply_record
  match "/confirm/:entry_hash" => "entries#confirm", :as => :job_apply_confirm
  match "/save/:entry_hash" => "entries#save", :as => :entry_video_save

  match "/entries/record" => "entries#record", :as => :job_apply_record
  match "/entries/exist" => "entries#exist", :as => :entry_video_exist

  match "/upgrade_browser" => "pages#upgrade_browser", :as => :upgrade_browser

  match "/candidates/:id/survey" => "candidates#survey", :as => :candidate_survey

  match "/candidates/:id/rate" => "candidates#rate", :as => :candidate_rate

  match "/candidates/:id/feedback" => "candidates#feedback", :as => :candidate_feedback

  resources :users, only: [:edit, :update]
  resources :employers, only: [:edit, :update]
  root :to => 'pages#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :job

  #has_many :responses
  has_many :entry_responses
  has_many :responses, :through => :entry_responses, :source => :response , :dependent => :destroy

  has_many :entry_video_responses
  has_many :video_responses, :through => :entry_video_responses, :source => :video_response , :dependent => :destroy

  attr_accessible :name, :email, :is_user_response

  devise :timeoutable

  # validations
  validates :name, :email, presence: :true

  # paperclips
  has_attached_file :temp_video, :storage => :s3, :use_timestamp => false, :path => "/:class/:id/temp_video/:filename", :s3_credentials => "#{Rails.root}/config/s3.yml"
  #validates_attachment_size :temp_video, :less_than => 10.megabyte

  has_attached_file :temp_audio, :storage => :s3, :use_timestamp => false, :path => "/:class/:id/temp_audio/:filename", :s3_credentials => "#{Rails.root}/config/s3.yml"
  #validates_attachment_size :temp_audio, :less_than => 10.megabyte

  has_attached_file :video,  :storage => :s3, :use_timestamp => false, :path => "/:class/:id/video/:filename", :s3_credentials => "#{Rails.root}/config/s3.yml"
  #validates_attachment_size :video, :less_than => 10.megabyte

  # state machine
  state_machine :state, :initial => :draft do
    event :invite do
      transition [:draft] => :invited
    end

    event :process do
      transition [:invited] => :processing
    end

    event :apply do
      transition [:processing] => :applied
    end

    event :review do
      transition [:applied] => :reviewed
    end

    after_transition :to => :invited, :do => :send_invitation
    after_transition :to => :processing, :do => :process_files
    after_transition :to => :applied, :do => :notify_employer
  end

  after_create :create_hash

  def ready_to_process?
    temp_video.exists? and temp_audio.exists?
  end

  def send_invitation
    EntryMailer.invite_email(self).deliver
  end

  def process_files
    EntryVideoWorker.perform_async(self.id)
  end

  def notify_employer
    EntryMailer.employer_notification_email(self).deliver
  end
  
  def create_hash
    if self.entry_hash.nil?
      salt = "asdjh208708asdfd0u098"
      self.entry_hash = Digest::MD5.hexdigest(self.id.to_s + salt)
      self.save
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_employer!, :except => [:apply, :save, :confirm,:exist]
  before_filter :set_job, :except => [:apply,:record, :save, :confirm,:exist]
  before_filter :check_for_valid_browser, :only => [:apply]

  def index
    @entries = @job.entries.all
  end

  def new
    @entry = @job.entries.new
  end

  def show
    @entry = @job.entries.find(params[:id])
  end

  def create
    @entry = @job.entries.new(params[:entry])
    if @entry.save
      @entry.invite
      redirect_to job_entries_path(@job), notice: "Candidate invitation sent successfully."
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    @entry = @job.entries.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to job_entries_path(@job), notice: "Entry deleted." }
      format.json { head :no_content }
    end
  end

  # entry application related

  def apply
    @entry = Entry.find_by_entry_hash(params[:entry_hash])
    @job = @entry.job
    render layout: "apply"
  end

  def record
    @entry = Entry.find_by_entry_hash(params[:entry_hash])
    @job = @entry.job
    @job.questions.each do |q|
        if (q.responses.count > 1)
          if (@entry.responses.where(:question_id => q.id).empty?)
            user_response = q.responses.find(params["content_#{q.id}"]).dup
            user_response.is_user_response = true
            @entry.responses << user_response
          end
        else
          if (@entry.responses.where(:question_id => q.id).empty?)
            @entry.responses.new(:content => params["content_#{q.id}"], :question_id => q.id, :is_user_response => true)
          end
        end
    end
    @video_question_index = 0
    @entry.save
    render layout: "apply"
  end

  def exist
    entries = Entry.where(:email => params[:email])
    entry_ids = entries.map {|e| e.id}
    entry_video_paths = entries.map {|e| e.video_file_name}
    render :json => {:entry_ids => entry_ids, :entry_video_paths => entry_video_paths}
  end

  def confirm
    @entry = Entry.find_by_entry_hash(params[:entry_hash])
    @job = @entry.job
    render layout: "apply"
  end

  def save
    @entry = Entry.find_by_entry_hash(params[:entry_hash])
    
    @entry.temp_video = params["video-blob"] if params["video-blob"]
    @entry.temp_audio = params["audio-blob"] if params["audio-blob"]
    @entry.save   # some times failing due to timeout : AWS::S3::Errors::RequestTimeout
                  # (Your socket connection to the server was not read from or written to within the timeout period.
                  # Idle connections will be closed.):
                  # app/controllers/entries_controller.rb:65:in `save'
    if @entry.ready_to_process?
      @entry.process
      render text: "finished"
    else
      render text: "Unable to process the recorded video"
    end
       
    
  end

  private 
    def set_job
      if params[:job_hash]
        @job = Job.find_by_job_hash(params[:job_hash])
      else
        @job = current_employer.jobs.find(params[:job_id])
      end
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/apply.html.erb
<div class="">
  <h3 id="job_title"><%= @job.title%></h3>
  <h5><%= @entry.name%></h5>
  <p id="job_desc"><%= @job.description%>.</p>

  <div class="question-mandatory-info">Questions marked with * are mandatory</div>
  
  <%= form_for @job , url: {action: "record"} do |f| %>

    <% @job.questions.each do |q| %>
        <%= f.label q.content %>
        <% if q.responses.count > 1 %>
           <% q.responses.optional_responses.each do |r| %>
                <%= radio_button_tag "content_#{q.id}", "#{r.id}" %>
                <%= f.label "content_#{q.id}", "#{r.content}", :class => "checkbox inline"%><br/>
           <% end %>
        <% elsif %>
            <%= text_field_tag("content_#{q.id}")%> </BR>
        <% end %>
    <% end %>
    <br/>
    <input type="submit" class="btn btn-primary btn-large" id="proceed" value="Proceed">
    <button class="btn btn-primary btn-large" id="skip"><%= t('buttons.skip') %></button>
  <% end %>





<script>
    var proceed = document.getElementById('proceed');

    proceed.onclick = function () {

    }

    skip.onclick = function() {
        window.location = "http://www.myspitch.com";
    }


</script>
</div>

app/views/entries/confirm.html.erb
<div class="hero-unit">
  <h3><%= t('entries.confirm.title')%></h3>
  <p></p>
</div>

app/views/entries/index.html.erb
<p class="lead"><%= t('entries.index.header') %> <b><%= @job.title%></b></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('entries.index.tables.name') %></th>
      <th><%= t('entries.index.tables.status') %></th>
      <th><%= t('entries.index.tables.created') %> at </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.name, job_entry_path(@job, entry), {} %></td>
        <td><%= entry.state %> </td>
        <td><%= entry.created_at.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= link_to (raw '<i class="icon-trash">'), [@job, entry], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('entries.index.invite_new_candidate'), new_job_entry_path(@job), {class: "btn btn-info"} %>

app/views/entries/new.html.erb
<p class="lead">Enter the details of the candidate.</p> 
<%= bootstrap_form_for([@job, @entry], help: :block) do |f| %>
  <%= f.alert_message  t('alerts.model_generic')  %>
  <%= f.text_field :name, label: t('entries.new.name.value') , help: t('entries.new.name.help'), class: "input-xlarge" %>
  <%= f.email_field :email, label: t('entries.new.email.value') , help:t('entries.new.email.help') , rows: 5, class: "input-xlarge"  %>
  <%= f.actions do %>
    <%= f.primary t('entries.new.invite'), disable_with: t('buttons.saving') %>
  <% end %>
<% end %>

app/views/entries/record.html.erb
<div class="hero-unit">
<h1 id="job_title"><%= @job.title%></h1>
<p id="job_desc"><%= @job.video_instructions%>.</p>
<p><%= @entry.name%></p>
<p><%= t('entries.Apply.welcome') %> <%= @job.employer.company_name%>.</p>
<p><%= t('entries.Apply.general_request') %> </p>  </BR>

<p id="record_request"><%= t('entries.Apply.record_request') %></p>
<p id="rec_to_start" class="hide"><%= t('entries.Apply.press_rec_to_start') %></p>

<div id = "counter"></div>

<video id="preview" controls style="width:320;height:240;"></video> <hr />
<audio id="preview-audio" class="hide"> </audio>

<p id="proceed_btn_title"><%= t('entries.Apply.proceed_btn_title')%></p>
<em id = "note"><%= t('entries.Apply.note')%></em>

<br/><br/><p id="skip_btn_title"><%= t('entries.Apply.skip_btn_title')%></p>

<button class="btn btn-primary btn-large" id="proceed"><%= t('buttons.proceed') %></button>
<button class="btn btn-primary btn-large hide" id="record"><%= t('buttons.record') %></button>
<button class="btn btn-primary btn-large" id="exist"><%= t('buttons.exist') %></button>
<button class="btn btn-primary btn-large" id="skip"><%= t('buttons.skip') %></button>
<button id="stop" disabled class="btn btn-primary btn-large hide"><%= t('buttons.stop') %></button>
<button class="btn btn-primary btn-large hide" id="submitRec"><%= t('buttons.submit_video') %></button>


<div class="hide" id="loader">
  <p><em id="submit_title"><%= t('entries.Apply.submitting')%></em></p>
  <p>
    <progress id='progressbar' max='100'></progress>
  </p>
</div>
<script>

    function PostBlob(blob, fileType, fileName) {
        // FormData
        var formData = new FormData();
        formData.append(fileType + '-filename', fileName);
        formData.append(fileType + '-blob', blob);
        var progress = document.getElementById('progressbar'); // = document.createElement('progress');
        // POST the Blob
        xhr('/save/<%= @entry.entry_hash%>', formData, progress, function(fileURL) {
            document.body.appendChild(document.createElement('hr'));
            var mediaElement = document.createElement(fileType);
            mediaElement.src = fileURL;
            mediaElement.controls = true;
            document.body.appendChild(mediaElement);
            mediaElement.play();
        });
    }

    var proceed = document.getElementById('proceed');
    var record = document.getElementById('record');
    var exist = document.getElementById('exist');
    var stop = document.getElementById('stop');
    var submitRec = document.getElementById('submitRec');
    var audio = document.querySelector('audio');

    var recordVideo = document.getElementById('record-video');
    var preview = document.getElementById('preview');
    var previewAudio = document.getElementById('preview-audio');

    preview.addEventListener("play", play_clicked, false);
    preview.addEventListener("pause", pause_clicked, false);
    preview.addEventListener("seeking", seeking_in_video, false);

    var originalStream = null;
    preview.src ='';

    var recordAudio, recordVideo;
    var is_camera_open = false;

    function openCamera()
    {
        $("preview").style.display ="block";
        if (is_camera_open)
        {

            if (originalStream != null) {
                preview.src = (window.webkitURL || window.URL).createObjectURL(originalStream);
                previewAudio.src = "";

            }
            preview.load();
            preview.play();


            return;

        }
        var video_constraints = {
            mandatory: { },
            optional: []
        };
        navigator.webkitGetUserMedia({
            audio: true,
            video: video_constraints
        }, function(stream) {
            //preview.autoplay = true;
            originalStream = stream;
            preview.src = (window.webkitURL || window.URL).createObjectURL(stream);
            preview.load();
            preview.play();

            preview.volume = 0;

            recordAudio = RecordRTC(stream);
            recordVideo = RecordRTC(stream, {
                type: 'video',
                video: {
                    width: 320,
                    height: 240
                },
                canvas: {
                    width: 320,
                    height: 240
                }
            });
        },function(stream) {});
        is_camera_open = true;
    }

    function cameraHide() {
        $("preview").css("visibility", "hidden");
    }

    proceed.onclick = function () {
        $("record").style.display ="block";
        $("rec_to_start").style.display ="block";

        $("proceed").hide();
        $("skip").hide();
        $("record_request").hide();
        $("proceed_btn_title").hide();
        $("note").hide();
        $("skip_btn_title").hide();
        $("submitRec").hide();

        openCamera();
    }

    exist.onclick = function () {
        debugger;
        new Ajax.Request('/entries/exist', {
            method:'post',
            parameters:{email: "<%= @entry.email%>"},
            onComplete: function(res) {
                var data = res.responseJSON;
                if (data.errors) {
                    console.log("error accured during save");
                } else {
                    debugger;
                  alert('Guy');

                }
            }
        });

//        var http = new XMLHttpRequest();
//        var url = "/entries/exist";
//        var params = "email=<%= @entry.email %>";
//        http.open("POST", url, true);
//
//        //Send the proper header information along with the request
//        http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
//        http.setRequestHeader("Content-length", params.length);
//        http.setRequestHeader("Connection", "close");
//
//        http.onreadystatechange = function() {//Call a function when the state changes.
//            if(http.readyState == 4 && http.status == 200) {
//                alert("Guy");
//                alert(http.responseText);
//            }
//        }
//        http.send(params);
    }

    skip.onclick = function() {
        window.location = "http://www.myspitch.com";
    }

    record.onclick = function() {

        try {

            openCamera();
            recordVideo.startRecording();
            recordAudio.startRecording();
        }
        catch(err)
        {
            // alert(I18n.t('entries.Apply.allow_alert'));
            // return;
        }
        // hide the record button
        $("record").hide();
        record.disabled = true;

        $("skip").hide();
        $("submitRec").hide();

        $("stop").style.display ="block";
        stop.disabled = false;

        $("rec_to_start").hide();

        $("counter").show();
        countdown(1, 00);
    };

    stop.onclick = function() {
        $("stop").hide();
        $("note").hide();
        $("counter").hide();

        record.disabled = false;

        $("proceed").style.display ="block";;
        proceed.disabled = false;
        $("proceed").innerHTML = 'Overwrite';

        $("submitRec").style.display ="block";
        submitRec.disabled = false;

        //cameraHide();
        recordAudio.stopRecording();
        recordVideo.stopRecording();
        clearTimeout(timer);


        url = window.URL.createObjectURL(recordVideo.getBlob());
        urlAudio = window.URL.createObjectURL(recordAudio.getBlob());


        preview.src = url;

        previewAudio.src = urlAudio;
        previewAudio.pause();
        preview.load();


    };

    function play_clicked() {
        // do something

        if (previewAudio.currentTime == 0)
        {
            previewAudio.load();
        }
        previewAudio.play();
    }

    function pause_clicked() {
        // do something
        var time = previewAudio.currentTime;

        previewAudio.pause();
        previewAudio.currentTime = time;
    }

    function seeking_in_video() {
        previewAudio.currentTime = preview.currentTime;
    }

    submitRec.onclick = function() {
        submitRec.disabled = true;
        $("submitRec").hide();
        $("exist").hide();
        //$("general_request").hide();
        $("rec_to_start").hide();
        $("record").hide();
        $("proceed").hide();

        var fileName = Math.round(Math.random() * 99999999) + 99999999;
        //show a loader
        $("loader").style.display ="block";;

        console.log(recordAudio.toUrl);
        PostBlob(recordAudio.getBlob(), 'audio', fileName + '.wav');
        PostBlob(recordVideo.getBlob(), 'video', fileName + '.webm');

        preview.src = '';
    };

    function xhr(url, data, progress, callback) {
        var request = new XMLHttpRequest();
        request.onreadystatechange = function() {
            if (request.readyState == 4 && request.status == 200 && request.responseText == "finished") {
                window.location = "/confirm/<%= @entry.entry_hash%>";
                //callback(location.href + request.responseText);
            }
        };

        request.upload.onload = function(e){
        }

        request.upload.onloadstart = function(e){
        }

        request.upload.onprogress = function(e) {
            if (e.total > 0)
            {
                var pValue = (e.loaded / e.total) * 97;
                if (pValue > $("progressbar").value) {
                    $("progressbar").value = pValue;
                }
            }
        };

        request.open('POST', url);
        request.send(data);
    }

    var timer;

    function countdown(minutes,secs) {

        var seconds = secs;
        var mins = minutes

        if (secs <= 0) {
            seconds = 60;
            mins--;
        }

        function tick() {
            //This script expects an element with an ID = "counter". You can change that to what ever you want.
            var counter = document.getElementById("counter");
            var current_minutes = mins;
            if (seconds >=0)
            {
                counter.innerHTML = current_minutes.toString() + ":" + (seconds < 10 ? "0" : "") + String(seconds);
            }
            seconds--;
            if( seconds >= -1 ) {
                timer = setTimeout(tick, 1000);
            } else {

                if(mins > 0){

                    countdown(mins-1,59);

                }
                else
                {
                    stop.onclick();
                }
            }
        }
        tick();
    }
</script>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.name%></h1>
<video width="320" height="240" controls>
  <source src="<%=@entry.video.url%>" type="video/webm">
</video>
<br/><br/>
<% @entry.responses.each do |r| %>
    <%= r.question.content %> <br/><br/>
    <% if r.question.responses.count > 1 %>
        <% r.question.responses.optional_responses.each do |q_res| %>
            <% if q_res.is_true %>
                <span id = "response_green"> <%= q_res.content %> </span>
            <% elsif q_res.content.eql?(r.content) && !q_res.is_true %>
                <span id = "response_red"> <%= q_res.content %>   </span>
            <% else %>
                <%= q_res.content %>
            <% end %>
        <% end %>
    <% else %>
        <%= r.content %>
    <% end %>

    <br/><br/>
<% end %>

<br/>


<br/>
<%= link_to t('entries.show.back_to_all') , job_entries_path(@job), {class: "btn btn-info"} %>