config/routes.rb
Myspitch::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :employers

  devise_for :users

  resources :jobs do
    resources :entries
  end

  resources :candidates

  resources :candidate_feedbacks

  match "/j/:entry_hash" => "entries#apply", :as => :job_apply_direct
  match "/record/:entry_hash" => "entries#record", :as => :job_apply_record
  match "/confirm/:entry_hash" => "entries#confirm", :as => :job_apply_confirm
  match "/save/:entry_hash" => "entries#save", :as => :entry_video_save

  match "/entries/record" => "entries#record", :as => :job_apply_record
  match "/entries/exist" => "entries#exist", :as => :entry_video_exist

  match "/upgrade_browser" => "pages#upgrade_browser", :as => :upgrade_browser

  match "/candidates/:id/survey" => "candidates#survey", :as => :candidate_survey

  match "/candidates/:id/rate" => "candidates#rate", :as => :candidate_rate

  match "/candidates/:id/feedback" => "candidates#feedback", :as => :candidate_feedback

  resources :users, only: [:edit, :update]
  resources :employers, only: [:edit, :update]
  root :to => 'pages#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :employer, foreign_key: "recruiter_id"
  has_many :entries, :dependent => :destroy
  has_many :questions, :dependent => :destroy
  has_many :video_questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :video_questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  attr_accessible :title, :description, :email_content, :questions_attributes, :video_questions_attributes

  devise :timeoutable

  validates :title, :email_content, presence: :true

  # paperclips
  has_attached_file :logo, :storage => :s3, :path => "/:class/:id/logo/:filename", :s3_credentials => "#{Rails.root}/config/s3.yml", :styles => { :small => "150x150>", :medium => "250x250>" }
  validates_attachment_size :logo, :less_than => 1.megabyte

  after_create :create_hash
  
  def create_hash
    if self.job_hash.nil?
      salt = "asdjh208708asdfd0u098"
      self.job_hash = Digest::MD5.hexdigest(self.id.to_s + salt)
      self.save
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_employer!

  def index
    @jobs = current_employer.jobs.all
  end

  def new
    @job = current_employer.jobs.new
  end

  def create
    @job = current_employer.jobs.new(params[:job])
    if @job.save
      redirect_to edit_job_path(@job), notice: "Job created successfully."
    else
      render :new
    end
  end

  def show
    @job = current_employer.jobs.find(params[:id])
  end

  def edit
    @job = current_employer.jobs.find(params[:id])
  end

  def update
    @job = current_employer.jobs.find(params[:id])
    @job.update_attributes(params[:job])
    if @job.valid?
      redirect_to jobs_path, notice: "Job updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @job = current_employer.jobs.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_path, notice: "Job deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= bootstrap_form_for(@job, help: :block) do |f| %>
  <%= f.alert_message t('alerts.model_generic') %>
  <%= f.text_field :title, help: t('activerecord.help.models.job.title'), class: "input-xxlarge" %>
  <%= f.text_area :email_content, help: t('activerecord.help.models.job.email_content'), rows: 5, class: "input-xxlarge wysihtml5"  %>

  <%= f.actions do %>
    <%= f.primary t('buttons.submit'), disable_with: t('buttons.saving') %>
  <% end %>
<% end %>

app/views/jobs/_instructions.html.erb
<%= bootstrap_form_for(@job, help: :block) do |f| %>
  <%= f.alert_message t('alerts.model_generic') %>
  <%= f.text_area :description, help: t('activerecord.help.models.job.description'), rows: 5, class: "input-xxlarge"  %>
  <%= f.text_area :video_instructions, help: t('activerecord.help.models.job.video_instructions'), rows: 5, class: "input-xxlarge"  %>
  <%= f.actions do %>
    <%= f.primary t('buttons.submit'), disable_with: t('buttons.saving') %>
  <% end %>
<% end %>

app/views/jobs/_preview_questions.html.erb
<%= bootstrap_form_for(@job, help: :block) do |f| %>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add Question", f, :questions %> </p>

  <%= f.actions do %>
    <%= f.primary t('buttons.submit'), disable_with: t('buttons.saving') %>
  <% end %>
<% end %>

app/views/jobs/_question_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :content, "Question" %>
    <%= link_to_remove_fields "Remove Question", f %><br />
    <%= f.text_area :content, :label => "Question Content", :rows => 3 %><br />
  </p>

  <div class="response-container">
    <ol class="sortable">
      <%= f.fields_for :responses,f.object.responses.optional_responses do |builder| %>
          <%= render 'response_fields', :f => builder %>
      <% end %>
    </ol>
    <p>
      <%= link_to_add_fields "Add Response", f, :responses %>
    </p>
  </div>

</div>

app/views/jobs/_response_fields.html.erb
<div class="fields">
<p>
  <%= f.label :content, "Response" %>
  <%= f.text_field :content , :label => "Response Content" %>
  <%= f.check_box :is_true ,:style => "display:inline;"%>
  <%= f.label :is_true, "Correct Response" , :style => "display:inline;" %></BR> </BR>
  <%= link_to_remove_fields "Remove Response", f %>
</p>
</div>

app/views/jobs/_video_question_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :content, "Question" %>
    <%= link_to_remove_fields "Remove Question", f %><br />
    <%= f.text_area :content, :label => "Question Content", :rows => 3 %><br />
    <%= f.text_field :max_duration, :label => "Maximum Video Length (in seconds)" %><br />
    <%= f.text_field :max_takes, :label => "Maximum Takes" %><br />
  </p>
</div>

app/views/jobs/_video_questions.html.erb
<%= bootstrap_form_for(@job, help: :block) do |f| %>
    <%= f.fields_for :video_questions do |builder| %>
        <%= render 'video_question_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Video Question", f, :video_questions %> </p>

    <%= f.actions do %>
        <%= f.primary t('buttons.submit'), disable_with: t('buttons.saving') %>
    <% end %>
<% end %>

app/views/jobs/edit.html.erb
<p class="lead">Edit <%= @job.title %>.</p> 

<ul id="myTab" class="nav nav-tabs">
  <li><a href="#general" data-toggle="tab">General</a></li>
  <li><a href="#instructions" data-toggle="tab">Instructions</a></li>
  <li><a href="#preview_q" data-toggle="tab">Preview Questions</a></li>
  <li><a href="#video_q" data-toggle="tab">Video Questions</a></li>
</ul>

<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade" id="general">
    <%= render partial: "form" %>
  </div>
  <div class="tab-pane fade" id="instructions">
    <%= render partial: "instructions" %>
  </div>
  <div class="tab-pane fade" id="preview_q">
    <%= render partial: "preview_questions" %>
  </div> 
  <div class="tab-pane fade" id="video_q">
    <%= render partial: "video_questions" %>
  </div>   
</div>
<div class="clearfix"></div>

<%= link_to t('entries.index.invite_new_candidate'), new_job_entry_path(@job), {class: "btn btn-info"} %></BR>
<%= link_to t('jobs.edit.show_candidates'), job_entries_path(@job), {} %> </BR>
<%= link_to t('jobs.edit.back_to_jobs'), jobs_path, {} %>

app/views/jobs/index.html.erb
<p class="lead"><%= t('jobs.index.header') %></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('jobs.index.tables.job') %></th>
      <th><%= t('jobs.index.tables.status') %></th>
      <th><%= t('jobs.index.tables.created') %> </th>
      <th><%= t('jobs.index.tables.entries') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, edit_job_path(job), {} %></td>
        <td></td>
        <td><%= job.created_at.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= link_to job.entries.count.to_s + " Candidates", job_entries_path(job), {} %></td>
        <td><%= link_to (raw '<i class="icon-trash">'), job, method: :delete, data: { confirm: t('buttons.sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('jobs.index.add_new_job') , new_job_path, {class: "btn btn-info"} %>

app/views/jobs/new.html.erb
<p class="lead"><%=t('jobs.new.content') %></p>
<%= render partial: "form" %>