config/routes.rb
Myspitch::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :employers

  devise_for :users

  resources :jobs do
    resources :entries
  end

  resources :candidates

  resources :candidate_feedbacks

  match "/j/:entry_hash" => "entries#apply", :as => :job_apply_direct
  match "/record/:entry_hash" => "entries#record", :as => :job_apply_record
  match "/confirm/:entry_hash" => "entries#confirm", :as => :job_apply_confirm
  match "/save/:entry_hash" => "entries#save", :as => :entry_video_save

  match "/entries/record" => "entries#record", :as => :job_apply_record
  match "/entries/exist" => "entries#exist", :as => :entry_video_exist

  match "/upgrade_browser" => "pages#upgrade_browser", :as => :upgrade_browser

  match "/candidates/:id/survey" => "candidates#survey", :as => :candidate_survey

  match "/candidates/:id/rate" => "candidates#rate", :as => :candidate_rate

  match "/candidates/:id/feedback" => "candidates#feedback", :as => :candidate_feedback

  resources :users, only: [:edit, :update]
  resources :employers, only: [:edit, :update]
  root :to => 'pages#index'
end

app/views/shared/_flashes.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert <%= flash_class(level) %>">
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">mySPitch</a>
      <% if current_employer %>
        <ul class="nav">
          <li><a href="<%= jobs_path %>">My Jobs</a></li>
        </ul>
        <ul class="nav">
          <li><a href="/candidates/show">My Candidates</a></li>
        </ul>
        <ul class="nav pull-right">
          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="<%=current_employer.profile_pic_url%>" width="25"/> <%= current_employer.fullname%> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%=edit_employer_path(current_employer)%>"><i class="icon-cog"></i> Edit Profile</a></li>
                <li><a href="<%=destroy_employer_session_path%> "><i class="icon-off"></i> Logout</a></li>
              </ul>
            </li>
          
        </ul>
      <% else %>
        <ul class="nav pull-right">
          <li><a href="<%= jobs_path %>">Already have an account?</a></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>